[package]
name = "mandelbrot"
version = "0.2.1"
authors = ["grubertw <grubertw@gmail.com>"]
edition = "2024"

[dependencies]
iced_wgpu="0.13.5"
iced_winit="0.13.0"
iced_widget="0.13.4"
bytemuck="1.24.0"
time="0.3.44"